name: Build LCM

on:
  push:
    branches: ["stage"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # download from s3 and place it in the current folder under .env file.
      - name: Download secrets and place it in .env file.
        run: curl https://22yards-image-bucket.s3.ap-south-1.amazonaws.com/manualUpload_2024-02-15T12%3A58%3A19%2B05%3A30 -o .env

      - name: Obtain tag
        id: tag
        run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"

      - name: Docker build image
        run:  |
          docker build -t api-server .
      - name: login to docker hub.
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: push to dockerhub.
        run: |
          docker tag api-server rithvik89/22yardz-api-server:${{ steps.tag.outputs.commit_id }}
          docker push rithvik89/22yardz-api-server:${{ steps.tag.outputs.commit_id }}
      # As of now db schema migration is happening within the node

      - name: SCP and Copy startup script.
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}
        run: |
          echo "${PRIVATE_KEY}" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./Makefile ./src/infra/db/schema.prisma ${USER_NAME}@${HOSTNAME}:/home/ubuntu/
      - name: ssh into node
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          sudo docker pull rithvik89/22yardz-api-server:${{ steps.tag.outputs.commit_id }}
          export var=$image_id
          echo "Checking" $var
          sed -i "s/^export image_id=.*/export image_id=${{ steps.tag.outputs.commit_id }}/" ~/.bashrc
          sed -i "s/^export prev_image_id=.*/export prev_image_id=$var/" ~/.bashrc
          source ~/.bashrc
          make apply_schema
          make restart_svc
          '